DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  login VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL
);

ALTER TABLE USER ADD CONSTRAINT unique_email UNIQUE (email);
